import type { Metadata } from "next";
import { Yaldevi } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { cn } from "@/lib/utils";
import Footer from "./_components/footer";

const inter = Yaldevi({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"bg-light")}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
